### ISSUE TITLE
 sample-executor 这个服务的作用是什么呢

### ISSUE THREAD

**Issue by hadoop835** [weibocom/rill-flow#29]
![image](https://github.com/weibocom/rill-flow/assets/8055054/f206ce4d-00c1-49ae-91b3-7808bdffdba5)

**Comment by qdaxb** [comment]
是个示例接口，quick start这个例子里编排了两次对sample-executor服务的http调用。

**Comment by hadoop835** [comment]
> 是个示例接口，quick start这个例子里编排了两次对sample-executor服务的http调用。

明白
